# Generated by Django 2.0 on 2024-02-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='dep_script',
            new_name='group_script',
        ),
    ]
